site_name: KrozFu

nav:
  - Home: index.md
  - Project:
    - Implementación WireGuard: articles/wireguard.md
    - Implementación Servidores: articles/servidor-ubuntu.md
  - Writeups:
    - HackTheBox:
      - Blue: writeups/hackthebox/blue.md

theme:
  name: material
  logo: img/kzf-notbk.png
  favicon: img/kzf-notbk.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/krozfu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/krozfu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/juan-carlos-charfuelan-caipe
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@krozfuhack

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/krozfu"  target="_blank" rel="noopener">KrozFu</a>