site_name: KrozFu

nav:
  - Whoami: index.md
  - Articles:
    - Configuración NAT y ataque con hping MikroTik: articles/nat-attack-hping.md
    - Implementación WireGuard: articles/wireguard.md
    - Implementación Servidores: articles/servidor-ubuntu.md
    - Instalar Kali Linux VMware: articles/kali-linux.md
  - Writeups:
    - HackTheBox:
      - Machines:
        - Blue: writeups/hackthebox/machines/blue.md
        - Lame: writeups/hackthebox/machines/lame.md
        - Cicada: writeups/hackthebox/machines/cicada.md
      - Challenges:
        - R0bob1rd: writeups/hackthebox/challenges/pwn/R0bob1rd.md
        - Primed-for-Action: writeups/hackthebox/challenges/coding/primed-for-action.md
    - TryHackMe:
      - Pickle Rick: writeups/tryhackme/pickle-rick.md

theme:
  name: material
  logo: img/kzf-logo.png
  favicon: img/kzf-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/juan-carlos-charfuelan-caipe
    - icon: fontawesome/brands/github-alt
      link: https://github.com/krozfu
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@krozfuhack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/krozfu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/krozfu/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/krozfu"  target="_blank" rel="noopener">KrozFu</a>