site_name: KrozFu
site_url: https://krozfu.github.io/

nav:
  - Whoami: index.md
  - Projects:
      - articles/index.md
      - Configuración NAT y ataque con hping MikroTik: articles/nat-hping/nat-attack-hping.md
      - Implementación WireGuard: articles/wireguard/wireguard.md
      - Implementación Servidores: articles/servidor/servidor-ubuntu.md
      - Instalar Kali Linux VMware: articles/kali-linux/kali-linux.md
      - Instalación PyPhi: articles/pyphi/install-pyphi.md
  - Writeups:
      - writeups/index.md
      - HackTheBox:
          - writeups/hackthebox/index.md
          - Machines:
              - Blue: writeups/hackthebox/machines/blue/blue.md
              - Lame: writeups/hackthebox/machines/lame/lame.md
              - Cicada: writeups/hackthebox/machines/cicada/cicada.md
              - Makesense: writeups/hackthebox/machines/makesense/makesense.md
          - Challenges:
              - Pwn:
                  - R0bob1rd: writeups/hackthebox/challenges/pwn/r0bob1rd.md
              - Coding:
                  - Primed-for-Action: writeups/hackthebox/challenges/coding/primed-for-action.md
              - Hardware:
                  - The-Needle: writeups/hackthebox/challenges/hardware/the-needle.md
              - IA/ML:
                  - Like-a-Gloves: writeups/hackthebox/challenges/ia-ml/like-a-gloves.md
      - TryHackMe:
          - Pickle Rick: writeups/tryhackme/pickle-rick/pickle-rick.md
      - Fluid Attacks CTF:
          - writeups/ctf-fluidattacks/index.md
          - "2026-2":
              - writeups/ctf-fluidattacks/2026-2/index.md

theme:
  name: material
  logo: img/kzf-logo.png
  favicon: img/kzf-logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: green
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: teal

extra_css:
  - stylesheets/extra.css

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/juan-carlos-charfuelan-caipe
    - icon: fontawesome/brands/github-alt
      link: https://github.com/krozfu
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@krozfuhack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/krozfu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/kr0zfu/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2026 <a href="https://github.com/krozfu"  target="_blank" rel="noopener">KrozFu</a>
